ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER PGUSER IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, DBA TO PGUSER;

DROP TABLE PUBLICTOILET;
DROP SEQUENCE PT_SEQ;

CREATE SEQUENCE PG_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PUBLICGYM (
    PG_NO NUMBER DEFAULT PG_SEQ.NEXTVAL CONSTRAINT PT_PK PRIMARY KEY,
    PG_NAME VARCHAR2(255),
    PG_AREA VARCHAR2(255),
    PG_SIZE NUMBER(20),
    PG_ADDR VARCHAR2(255),
    PG_DATE DATE
);

CREATE INDEX PT_ADDR_IDX ON PUBLICTOILET(PT_ADDR);

SELECT COUNT(*) FROM PUBLICTOILET;

DELETE FROM PUBLICTOILET;
commit;